# Generated by Django 4.0.3 on 2022-05-29 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
