# Generated by Django 4.0.3 on 2022-05-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_number_of_questions_quiz_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='true_answer',
            field=models.CharField(choices=[(models.CharField(max_length=280, null=True), 'option 1'), (models.CharField(max_length=280, null=True), 'option 2'), (models.CharField(max_length=280, null=True), 'option 3'), (models.CharField(max_length=280, null=True), 'option 4')], default=models.CharField(max_length=280, null=True), max_length=280),
        ),
    ]
