# Generated by Django 4.0.3 on 2022-05-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_true_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='true_answer',
            field=models.CharField(blank=True, choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], default=models.CharField(max_length=280, null=True), max_length=280, null=True),
        ),
    ]
