# Generated by Django 4.0.3 on 2022-05-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_question_true_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz_score',
        ),
    ]
