# Generated by Django 4.0.3 on 2022-05-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_alter_tag_description_learningmaterialvideos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningmaterialvideos',
            old_name='seq_number',
            new_name='sequence',
        ),
    ]
