# Generated by Django 4.0.3 on 2022-05-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_rename_seq_number_learningmaterialvideos_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
