# Generated by Django 4.0.3 on 2022-05-23 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_alter_space_spaceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterialvideos',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='space/videos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='spaceImage',
            field=models.ImageField(upload_to='space/images/learningSpaceThumb'),
        ),
    ]
