# Generated by Django 4.0.3 on 2022-05-31 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0009_rename_video_learningmaterials_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='space',
            name='spaceImage',
            field=models.ImageField(null=True, upload_to='space/images/learningSpaceThumb'),
        ),
    ]
