# Generated by Django 4.0.3 on 2022-05-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0011_alter_space_author_alter_space_spaceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='spaceImage',
            field=models.ImageField(blank=True, null=True, upload_to='space/images/learningSpaceThumb'),
        ),
    ]
